# Generated by Django 5.2.7 on 2026-05-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_communication_records_hub'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationlog',
            new_name='communicati_status_f6bf05_idx',
            old_name='communicati_status_crat_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationlog',
            new_name='communicati_clinic__cbb0e2_idx',
            old_name='communicati_clinic_stat_idx',
        ),
    ]
