# Generated by Django 5.2.7 on 2026-06-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('notifications', '0007_rename_communicati_status_crat_idx_communicati_status_f6bf05_idx_and_more'),
        ('patients', '0028_patient_home_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='notification',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clinics.practitioner'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_BOOKING', 'New Appointment Booking'), ('NEW_CLIENT', 'New Client'), ('ONLINE_BOOKING', 'New Online Booking'), ('DAILY_SUMMARY', 'Daily Appointments Summary')], db_index=True, max_length=30),
        ),
    ]
