# Generated by Django 5.2.7 on 2026-09-08 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Template content supporting variables like {{ name }}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboundSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_number', models.CharField(max_length=20)),
                ('recipient_number', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(db_index=True, max_length=255)),
                ('processed_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.gatewaydevice')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.provider')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_number', models.CharField(help_text='E.164 formatted number, e.g. +639XXXXXXXXX', max_length=20)),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('UNDELIVERED', 'Undelivered'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of send attempts made')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, help_text='Maximum allowed retries before terminal failure')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_device', models.ForeignKey(blank=True, help_text='The gateway device that claimed and sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.gatewaydevice')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='smsgateway.smsmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['status', 'scheduled_time'], name='smsgateway__status_76f98d_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['recipient_number'], name='smsgateway__recipie_77e486_idx'),
        ),
    ]
