import malasakitLogo from '@/assets/malasakit/Primary Logo - Colored.svg';

/**
 * Reusable branding footer for all printed/exported documents.
 * Place at the very bottom of any A4 print template or PDF view.
 */
export const DocumentFooter: React.FC = () => (
  <div
    style={{
      marginTop: '24px',
      paddingTop: '14px',
      borderTop: '1px solid #e5e7eb',
      textAlign: 'center',
    }}
  >
    <img
      src={malasakitLogo}
      alt="Malasakit PMS"
      style={{ height: '20px', display: 'block', margin: '0 auto 4px' }}
    />
    <p style={{ fontSize: '10px', color: '#9ca3af', margin: 0 }}>
      This is generated by Malasakit PMS
    </p>
  </div>
);
