# Generated by Django 5.2.7 on 2026-04-25 02:54

import apps.appointments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_blockappointment_visibility_type'),
        ('patients', '0014_clientformrequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebookingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.appointments.models._default_rebooking_expires)),
                ('is_used', models.BooleanField(default=False, help_text='True once the patient has used this link to rebook.')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(help_text='The original missed/declined appointment this link relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_links', to='appointments.appointment')),
                ('new_appointment', models.ForeignKey(blank=True, help_text='The new appointment created when the patient used this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_rebooking_links', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_links', to='patients.patient')),
            ],
            options={
                'db_table': 'rebooking_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='rebooking_l_token_b627bb_idx'), models.Index(fields=['patient', 'is_used'], name='rebooking_l_patient_e71d6b_idx')],
            },
        ),
    ]
