# Generated by Django 5.2.7 on 2026-05-12 02:22

import apps.appointments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_calendarnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentConfirmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.appointments.models._default_confirm_expires)),
                ('is_used', models.BooleanField(default=False, help_text='True once the patient has clicked Confirm.')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(help_text='The appointment this token is for.', on_delete=django.db.models.deletion.CASCADE, related_name='confirm_tokens', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_confirm_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='appointment_token_b9dc84_idx'), models.Index(fields=['appointment', 'is_used'], name='appointment_appoint_f885d8_idx')],
            },
        ),
    ]
