# Generated by Django 5.2.7 on 2026-05-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_blockappointment_practitioner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blockappointment',
            new_name='block_appoi_practit_35b2d6_idx',
            old_name='block_appts_prac_date_idx',
        ),
    ]
