# Generated by Django 5.2.7 on 2026-04-25 06:46

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_cliniccommunicationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[apps.common.validators.validate_ph_phone]),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=15, validators=[apps.common.validators.validate_ph_phone]),
        ),
    ]
