# Generated by Django 5.2.7 on 2026-05-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_per_reminder_type_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniccommunicationsettings',
            name='booking_confirmation_method',
            field=models.CharField(choices=[('EMAIL', 'Email Only'), ('SMS', 'SMS Only'), ('BOTH', 'Email & SMS')], default='EMAIL', help_text='Channel for booking confirmations.', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliniccommunicationsettings',
            name='reminder_method',
            field=models.CharField(choices=[('EMAIL', 'Email Only'), ('SMS', 'SMS Only'), ('BOTH', 'Email & SMS')], default='EMAIL', help_text='Channel for appointment reminders.', max_length=5),
        ),
    ]
