# Generated by Django 5.2.7 on 2026-06-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_clinicconsentform'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicconsentform',
            new_name='clinic_cons_clinic__421572_idx',
            old_name='clinic_cons_clinic__idx',
        ),
    ]
