# Generated by Django 5.2.7 on 2026-06-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0020_cliniccommunicationsettings_dna_followup_delay_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public URL slug for this clinic branch (e.g. cebu-clinic)', max_length=200, null=True, unique=True),
        ),
    ]
