# Generated by Django 5.2.7 on 2026-06-27 11:39

import django.db.models.deletion
from django.db import migrations, models


def migrate_consent_forms(apps, schema_editor):
    ClinicConsentForm = apps.get_model('clinics', 'ClinicConsentForm')
    
    clinics_with_forms = ClinicConsentForm.objects.values_list('clinic_id', flat=True).distinct()
    
    for clinic_id in clinics_with_forms:
        forms = ClinicConsentForm.objects.filter(clinic_id=clinic_id).order_by('-created_at')
        active_forms = forms.filter(is_active=True)
        if active_forms.exists():
            keep_form = active_forms.first()
        else:
            keep_form = forms.first()
            
        forms.exclude(id=keep_form.id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0021_clinic_slug'),
    ]

    operations = [
        migrations.RunPython(migrate_consent_forms),
        migrations.AlterField(
            model_name='clinicconsentform',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_form', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicconsentform',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If true, this branch requires this consent form to be signed'),
        ),
    ]
