# Generated by Django 5.2.7 on 2026-06-27 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0022_refactor_clinic_consent_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconsentform',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initially created the form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consent_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicconsentform',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_consent_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
