import React from 'react';
import { DocCallout } from '../DocCallout';
import { ScreenshotPlaceholder } from '../ScreenshotPlaceholder';

const Chapter28: React.FC = () => {
  return (
    <>
      <p className="text-xl text-gray-500 font-body mb-8">
        Learn how to monitor clinic income, track patient payments, and evaluate billing performance using comprehensive Financial Reports.
      </p>

      {/* IMPORTANT CONCEPT — Financial Reporting Workflow */}
      <div className="bg-sky-50 border-l-4 border-sky-500 p-6 md:p-8 rounded-r-2xl mb-12">
        <h3 className="text-xl font-bold text-sky-900 mb-4">Financial Reporting Workflow</h3>
        
        <p className="text-gray-700 font-body mb-4">
          Financial Reports in Malasakit combine raw invoice data and recorded payment transactions to provide a complete overview of your clinic's financial health. These reports are essential tools for finance teams and owners to reconcile daily collections, track outstanding receivables, and project future revenue.
        </p>

        <div className="bg-white p-5 rounded-xl border border-sky-100 shadow-[0_4px_12px_rgb(14,165,233,0.1)] mb-6 text-center overflow-x-auto">
          <p className="text-sm font-semibold text-gray-800 mb-2">Reporting Data Pipeline</p>
          <div className="flex flex-wrap items-center justify-center gap-2 sm:gap-4 text-[13px] text-gray-600 font-mono">
            <span className="px-3 py-1.5 bg-gray-50 rounded border border-gray-200">Invoices</span>
            <span className="text-sky-400">→</span>
            <span className="px-3 py-1.5 bg-gray-50 rounded border border-gray-200">Payments</span>
            <span className="text-sky-400">→</span>
            <span className="px-3 py-1.5 bg-sky-50 rounded border border-sky-200">Revenue</span>
            <span className="text-sky-400">→</span>
            <span className="px-3 py-1.5 bg-amber-50 rounded border border-amber-200">Financial Reports</span>
            <span className="text-sky-400">→</span>
            <span className="px-3 py-1.5 bg-emerald-50 text-emerald-700 font-bold rounded border border-emerald-200">Business Insights</span>
          </div>
        </div>

        <ScreenshotPlaceholder label="Diagram 28.1: Financial Reporting Workflow. Caption: 'Financial Reports combine invoices and payment data to provide a complete financial overview.'" />
      </div>


      {/* SECTION 28.1 — Revenue Reports */}
      <h3 className="text-2xl font-semibold text-trust-harbor font-heading mt-12 mb-4 border-b border-gray-100 pb-2">
        28.1 Revenue Reports
      </h3>
      <p className="text-gray-700 font-body mb-6">Summarizing clinic income over specific periods.</p>

      <div className="space-y-8">
        <div className="bg-white rounded-2xl shadow-[0_2px_10px_rgb(0,0,0,0.04)] border border-gray-100 p-6 md:p-8">
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            Revenue Reports calculate and summarize the total financial income generated by the clinic. Staff can use the filtering panel to define exact <strong>Date Ranges</strong> (From Date → To Date), select specific <strong>Clinic Branches</strong>, or filter by individual <strong>Practitioners</strong>.
          </p>
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            The report displays critical high-level metrics including:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700 font-body mb-6">
            <li><strong>Total Revenue:</strong> The aggregate income collected during the selected timeframe.</li>
            <li><strong>Revenue by Branch:</strong> A comparative breakdown of income generated per location.</li>
            <li><strong>Revenue by Practitioner:</strong> Individual income contributions from staff members.</li>
            <li><strong>Revenue Trends:</strong> Visual representations mapping income growth or decline.</li>
          </ul>

          <ScreenshotPlaceholder label="Screenshot 28.1: Revenue Report page. Highlight Revenue summary cards. Caption: 'Revenue Reports summarize clinic income over the selected reporting period.'" />
          <ScreenshotPlaceholder label="Screenshot 28.2: Revenue filters. Highlight Date range and branch filters. Caption: 'Filter revenue reports by date range, branch, or practitioner where available.'" />
          
          <div className="mt-8">
            <ScreenshotPlaceholder label="Diagram 28.2: Revenue Logic. Caption: 'Revenue Reports summarize financial activity from completed invoice payments.'" />
          </div>
        </div>
      </div>

      <DocCallout type="info">
        Revenue reports are most useful when reviewed over consistent reporting periods (e.g., weekly, monthly, or quarterly) to accurately gauge financial trends.
      </DocCallout>


      {/* SECTION 28.2 — Payment Reports */}
      <h3 className="text-2xl font-semibold text-trust-harbor font-heading mt-16 mb-4 border-b border-gray-100 pb-2">
        28.2 Payment Reports
      </h3>
      <p className="text-gray-700 font-body mb-6">Tracking the history of recorded collections.</p>

      <div className="space-y-8">
        <div className="bg-white rounded-2xl shadow-[0_2px_10px_rgb(0,0,0,0.04)] border border-gray-100 p-6 md:p-8">
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            While Revenue Reports provide high-level summaries, Payment Reports offer a granular, line-by-line breakdown of every single transaction processed by the clinic. This is the primary tool used by finance teams to reconcile daily cash drawers and bank transfers.
          </p>
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            The Payment Report table logs crucial data for every transaction:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700 font-body mb-6">
            <li><strong>Payment Amount & Date</strong></li>
            <li><strong>Payment Method</strong> (e.g., Cash, Credit Card)</li>
            <li><strong>Invoice Reference Number</strong></li>
            <li><strong>Associated Patient & Practitioner</strong></li>
          </ul>

          <ScreenshotPlaceholder label="Screenshot 28.3: Payment Report. Highlight Payment history table. Caption: 'Payment Reports provide a complete history of recorded clinic payments.'" />
          <ScreenshotPlaceholder label="Screenshot 28.4: Payment details. Highlight Payment information. Caption: 'Payment Reports display detailed financial transaction records.'" />
          
          <div className="mt-8">
            <ScreenshotPlaceholder label="Diagram 28.3: Payment History. Caption: 'Every recorded payment contributes to the clinic's payment reporting history.'" />
          </div>
        </div>
      </div>

      <DocCallout type="tip">
        Review payment reports regularly (ideally at the end of each business day) to reconcile collections and quickly identify any missing or outstanding transactions.
      </DocCallout>


      {/* SECTION 28.3 — Invoice Reports */}
      <h3 className="text-2xl font-semibold text-trust-harbor font-heading mt-16 mb-4 border-b border-gray-100 pb-2">
        28.3 Invoice Reports
      </h3>
      <p className="text-gray-700 font-body mb-6">Monitoring billing performance and outstanding debt.</p>

      <div className="space-y-8">
        <div className="bg-white rounded-2xl shadow-[0_2px_10px_rgb(0,0,0,0.04)] border border-gray-100 p-6 md:p-8">
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            The Invoice Report functions as the clinic's accounts receivable ledger. It tracks the billing status of every invoice generated across the system, allowing finance staff to actively monitor incoming cash flow and pursue outstanding debts.
          </p>
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            By filtering invoices by status, staff can rapidly isolate problematic accounts:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700 font-body mb-6">
            <li><strong>Unpaid & Partially Paid:</strong> Highlights accounts with outstanding balances requiring immediate follow-up or collection efforts.</li>
            <li><strong>Generated / Draft:</strong> Identifies invoices that have been created but not yet finalized or issued to the patient.</li>
            <li><strong>Paid:</strong> Confirms invoices where the financial obligation has been completely fulfilled.</li>
          </ul>

          <ScreenshotPlaceholder label="Screenshot 28.5: Invoice Report. Highlight Invoice status table. Caption: 'Invoice Reports summarize the billing status of every generated invoice.'" />
          <ScreenshotPlaceholder label="Screenshot 28.6: Outstanding invoices. Highlight Remaining balances. Caption: 'Outstanding invoices help finance staff identify unpaid or partially paid accounts.'" />
          
          <div className="mt-8">
            <ScreenshotPlaceholder label="Diagram 28.4: Invoice Tracking. Caption: 'Invoice Reports provide visibility into clinic billing activity.'" />
          </div>
        </div>
      </div>

      <DocCallout type="important">
        Invoice Reports should always be reviewed in tandem with Payment Reports to obtain a holistic, accurate picture of the clinic's financial performance.
      </DocCallout>


      {/* SECTION 28.4 — Role-Based Financial Visibility */}
      <h3 className="text-2xl font-semibold text-trust-harbor font-heading mt-16 mb-4 border-b border-gray-100 pb-2">
        28.4 Role-Based Financial Visibility
      </h3>
      <p className="text-gray-700 font-body mb-6">How permissions protect sensitive business data.</p>

      <div className="space-y-8">
        <div className="bg-white rounded-2xl shadow-[0_2px_10px_rgb(0,0,0,0.04)] border border-gray-100 p-6 md:p-8">
          <p className="text-gray-700 font-body leading-relaxed mb-6">
            Financial reports contain the clinic's most sensitive operational data. Consequently, Malasakit strictly enforces Role-Based Access Control (RBAC) to ensure staff only see the financial data they are explicitly authorized to view:
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            <div className="p-5 bg-sky-50 rounded-xl border border-sky-200">
              <h4 className="font-bold text-sky-900 mb-2">Owner</h4>
              <p className="text-sm text-gray-700">Unrestricted access. Owners can view and compare organization-wide financial reports across all clinic branches.</p>
            </div>
            <div className="p-5 bg-gray-50 rounded-xl border border-gray-200">
              <h4 className="font-bold text-gray-900 mb-2">Manager</h4>
              <p className="text-sm text-gray-700">Restricted access. Managers can generate financial reports exclusively for the specific branches they are assigned to.</p>
            </div>
            <div className="p-5 bg-gray-50 rounded-xl border border-gray-200 md:col-span-2">
              <h4 className="font-bold text-gray-900 mb-2">Finance, Front Desk & Practitioners</h4>
              <p className="text-sm text-gray-700">Finance staff access reports based on their explicit permissions. Front Desk and Practitioners generally have highly restricted or zero access to global financial reports unless explicitly granted by an Owner.</p>
            </div>
          </div>

          <ScreenshotPlaceholder label="Screenshot 28.7: Owner Financial Report. Highlight Organization-wide data. Caption: 'Owners can review financial information across every clinic branch.'" />
          <ScreenshotPlaceholder label="Screenshot 28.8: Manager Financial Report. Highlight Branch-specific information. Caption: 'Managers only access financial reports for their assigned clinic branches.'" />
          
          <div className="mt-8">
            <ScreenshotPlaceholder label="Diagram 28.5: Security Workflow. Caption: 'Role-Based Access Control protects sensitive financial information.'" />
          </div>
        </div>
      </div>

      {/* CHAPTER SUMMARY */}
      <h3 className="text-2xl font-semibold text-trust-harbor font-heading mt-16 mb-4 border-b border-gray-100 pb-2">
        Summary
      </h3>
      <p className="text-gray-700 font-body leading-relaxed mb-4">
        In this chapter, you learned how to evaluate the clinic's financial health using the Reporting module. You should now understand:
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-700 font-body">
        <li>How <strong>Revenue Reports</strong> summarize high-level clinic income across specific date ranges and branches.</li>
        <li>How <strong>Payment Reports</strong> provide a granular transaction ledger used for daily cash reconciliation.</li>
        <li>How <strong>Invoice Reports</strong> track billing statuses to help staff identify and pursue outstanding patient balances.</li>
        <li>How the system's strict <strong>Role-Based Visibility</strong> protects sensitive financial data from unauthorized staff.</li>
      </ul>
    </>
  );
};

export default Chapter28;
