# Generated by Django 5.2.7 on 2026-06-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_address_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='custom_contact_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
