# Generated by Django 5.2.7 on 2026-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientconsent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientconsent',
            new_name='patient_con_portal__e46049_idx',
            old_name='patient_cons_portal__f54593_idx',
        ),
        migrations.RenameIndex(
            model_name='patientconsent',
            new_name='patient_con_patient_909d7b_idx',
            old_name='patient_cons_patient_0cb527_idx',
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
