# Generated by Django 5.2.7 on 2026-04-25 06:46

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_portalbooking_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, validators=[apps.common.validators.validate_ph_phone]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, validators=[apps.common.validators.validate_ph_phone]),
        ),
    ]
