# Generated by Django 5.2.7 on 2026-06-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_appointment_service_overridden'),
        ('patients', '0025_patientconsentdocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientconsentdocument',
            new_name='patient_con_patient_ec0cac_idx',
            old_name='patient_con_patient__idx',
        ),
        migrations.RenameIndex(
            model_name='patientconsentdocument',
            new_name='patient_con_clinic__4782d1_idx',
            old_name='patient_con_clinic__idx',
        ),
        migrations.RenameIndex(
            model_name='patientconsentdocument',
            new_name='patient_con_appoint_58add7_idx',
            old_name='patient_con_appoint_idx',
        ),
        migrations.AlterField(
            model_name='patientconsentdocument',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_documents', to='appointments.appointment'),
        ),
    ]
