# Generated by Django 5.2.7 on 2026-06-23 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0020_cliniccommunicationsettings_dna_followup_delay_hours'),
        ('patients', '0027_add_data_privacy_consent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='home_branch',
            field=models.ForeignKey(blank=True, help_text='The specific clinic branch this patient belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_patients', to='clinics.clinic'),
        ),
    ]
