# Generated by Django 5.2.7 on 2026-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_alter_patientcase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send SMS notifications for appointment reminders (when SMS is enabled).'),
        ),
    ]
