# Generated by Django 5.2.7 on 2026-04-25 06:46

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_staff_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[apps.common.validators.validate_ph_phone]),
        ),
    ]
