# Generated by Django 5.2.7 on 2026-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_rotation',
            field=models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Automatic password rotation schedule', max_length=10),
        ),
    ]
