# Generated by Django 5.2.7 on 2026-05-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rbac_permission_groups'),
        ('clinics', '0014_alter_clinic_phone_alter_location_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepermission',
            name='feature_key',
            field=models.CharField(help_text='One of the FEATURE_KEYS constants.', max_length=100),
        ),
        migrations.AlterField(
            model_name='featurepermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='clinic',
            field=models.ForeignKey(help_text='The clinic this permission group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Protected groups (e.g. Owner) cannot be deleted.'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='is_system_template',
            field=models.BooleanField(default=False, help_text='System-seeded defaults; one per clinic per role template.'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='role_template',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('FRONTDESK', 'Frontdesk'), ('PRACTITIONER', 'Practitioner'), ('CUSTOM', 'Custom')], default='CUSTOM', help_text='Starting template used to seed default permissions.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_group',
            field=models.ForeignKey(blank=True, help_text='The RBAC permission group assigned to this user. Overrides role-based defaults for feature-level access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.permissiongroup'),
        ),
    ]
