# Generated by Django 5.2.7 on 2026-05-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_featurepermission_feature_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces the user to set a new password before accessing the application.'),
        ),
    ]
