# Generated by Django 5.2.7 on 2026-05-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_multirole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolechangelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
