# Generated by Django 5.2.7 on 2026-06-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_branch_access'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userbranchaccess',
            new_name='user_branch_user_id_64cb9a_idx',
            old_name='uba_user_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='userbranchaccess',
            new_name='user_branch_branch__7d8627_idx',
            old_name='uba_branch_idx',
        ),
    ]
