# Generated by Django 5.2.7 on 2026-07-19 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('patients', '0030_patientcasesessionlog'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('CLINICAL_NOTE', 'Clinical Note'), ('LETTER', 'Letter'), ('REPORT', 'Report'), ('LAB_RESULT', 'Lab Result'), ('IMAGING', 'Imaging'), ('REFERRAL', 'Referral'), ('INSURANCE', 'Insurance'), ('ATTACHMENT', 'Attachment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Manual Upload'), ('CLINICAL_NOTE', 'Clinical Note'), ('LETTER', 'Letter'), ('REPORT', 'Report')], default='UPLOAD', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='PK of the source record (ClinicalNote, Letter, etc.)', null=True)),
                ('file', models.FileField(upload_to='case_documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='patients.patient')),
                ('patient_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='patients.patientcase')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_case_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'patient_case', '-created_at'], name='case_docume_patient_c8ebb6_idx'), models.Index(fields=['clinic', 'category'], name='case_docume_clinic__781e36_idx'), models.Index(fields=['source_type', 'source_id'], name='case_docume_source__3054f5_idx')],
            },
        ),
    ]
