# Generated by Django 5.2.7 on 2026-07-19 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('patients', '0030_patientcasesessionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('REFERRAL', 'Referral Letter'), ('REPORT', 'Clinical Report'), ('GENERAL', 'General Letter'), ('MEDICAL_CERT', 'Medical Certificate'), ('CUSTOM', 'Custom')], default='GENERAL', max_length=20)),
                ('content_html', models.TextField(help_text='Rich-text HTML body with merge-field placeholders e.g. {{patient.full_name}}')),
                ('header_html', models.TextField(blank=True, default='', help_text='Custom header HTML override. Empty = use clinic defaults.')),
                ('footer_html', models.TextField(blank=True, default='', help_text='Custom footer HTML override. Empty = use clinic defaults.')),
                ('include_logo', models.BooleanField(default=True)),
                ('include_signature', models.BooleanField(default=True)),
                ('merge_fields', models.JSONField(blank=True, default=list, help_text='List of available merge field keys for this template')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(help_text='Template is scoped to this clinic', on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letter_templates', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='letters.lettertemplate')),
            ],
            options={
                'db_table': 'letter_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('content_html', models.TextField(help_text='Final rendered HTML with merge fields resolved')),
                ('rendered_pdf', models.FileField(blank=True, help_text='Cached PDF version of this letter', null=True, upload_to='letters/pdfs/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('SENT', 'Sent')], default='DRAFT', max_length=10)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, default='', help_text='Base64-encoded PNG digital signature')),
                ('sent_to', models.JSONField(blank=True, default=list, help_text='List of recipient email addresses')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='patients.patient')),
                ('patient_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='patients.patientcase')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='clinics.practitioner')),
                ('template', models.ForeignKey(blank=True, help_text='Source template (audit reference only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='letters.lettertemplate')),
            ],
            options={
                'db_table': 'letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lettertemplate',
            index=models.Index(fields=['clinic', 'is_active'], name='letter_temp_clinic__ae9975_idx'),
        ),
        migrations.AddIndex(
            model_name='lettertemplate',
            index=models.Index(fields=['category'], name='letter_temp_categor_64a896_idx'),
        ),
        migrations.AddConstraint(
            model_name='lettertemplate',
            constraint=models.UniqueConstraint(fields=('clinic', 'name', 'version'), name='unique_letter_template_version_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['patient', '-created_at'], name='letters_patient_28bbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['patient_case', '-created_at'], name='letters_patient_373dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['clinic', '-created_at'], name='letters_clinic__984024_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['status'], name='letters_status_f0b599_idx'),
        ),
    ]
