# Generated by Django 5.2.7 on 2026-07-16 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0008_clinicalnote_patient_case_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='amendment_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ClinicalNoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('encrypted_content', models.TextField(blank=True, default='', help_text='AES encrypted JSON content snapshot')),
                ('chart_annotation_data', models.JSONField(blank=True, null=True)),
                ('amendment_reason', models.TextField(blank=True, default='')),
                ('clinical_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clinical_templates.clinicalnote')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_note_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_note_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['clinical_note', 'version_number'], name='clinical_no_clinica_4cd53c_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinical_note', 'version_number'), name='unique_note_version')],
            },
        ),
    ]
