# Generated by Django 5.2.7 on 2026-09-08 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly name for this device (e.g. 'Clinic A - Samsung A55')", max_length=255)),
                ('device_identifier', models.CharField(db_index=True, default=uuid.uuid4, help_text='Unique identifier supplied by the Android app (e.g. ANDROID-GATEWAY-001 or Android device UUID)', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='The SIM phone number on this device (E.164)', max_length=20)),
                ('device_token', models.CharField(db_index=True, help_text='Secret token used by the device to authenticate with the API — never expose in list views', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the device polled or sent a heartbeat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal name for the provider configuration', max_length=255)),
                ('provider_type', models.CharField(help_text='Identifier for the provider integration (e.g., LOCAL, SMPP, HTTP)', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('gateway_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.gatewaydevice')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.provider')),
            ],
        ),
    ]
